### ISSUE TITLE
Add an index for `queue`

### ISSUE THREAD

**Issue by contentfree** [collectiveidea/delayed_job_mongoid#41]
When using queues, things can get slow: findAndModify locks the table while a BasicCursor goes through each row. Ensuring a `{queue: 1}` index exists clears things up.

**Comment by msaspence** [comment]
I found that by adding a { queue: 1 } index certainly helps but to get best performance you need { "queue" : 1, "locked_by" : -1, "priority" : 1, "run_at" : 1 }. I don't entirely understand why but looking at the explain it means avoiding a sort or any kind.

**Comment by rdetert** [comment]
@msaspence where would I put that line. In a Mongoid model or typing it directly into the mongodb console?

**Comment by msaspence** [comment]
I ran it directly on the Mongo console as that is how we manage our indexes (preferring to have them documented in a single wiki page, rather than spread out across numerous ruby files, we could probably condense them into a single ruby file so they can be programmatically run and in a single location, but I digress).

```
db.delayed_jobs.ensureIndex({ "queue" : 1, "locked_by" : -1, "priority" : 1, "run_at" : 1 }, {"background": true})
```

If you wanted to define it in ruby I believe you could do something like this in an initializer or something, but I haven't actually run this:

```
Delayed::Job.index({ queue: 1, locked_by: -1, priority: 1, run_at: 1 }, { background: true })
```

**Comment by dblock** [comment]
This is old. Doing some bookkeeping. Anyone cares to figure out what to do with this issue? Related to #44?

**Comment by johnnyshields** [comment]
This is done, we have already added the suggested index:

```
          index queue: 1, locked_by: -1, priority: 1, run_at: 1
```
